version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_gvsv
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvsv
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_gvsv
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq