# Generated by Django 5.1.3 on 2024-12-03 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(default='male', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('avatar', models.CharField(default='/static/images/default_avatar.jpg', max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('role', models.IntegerField(default=0)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
